# Serveur Minecraft Vote
# https://serveur-minecraft-vote.fr/

rewards:
  1:
    percent: 10
    needToBeOnline: false # Player must not be online to receive the reward
    commands:
      - "eco give %player% 100"
    broadcast:
      - "&f%player% &7just won &a$100"
  2:
    percent: 30
    needToBeOnline: true # Player must be online to receive the reward
    commands:
      - "give %player% minecraft:stone 10"
    broadcast:
      - "&f%player% &7just won &ax10 stone"      
  3:
    percent: 30
    needToBeOnline: false # Player must not be online to receive the reward
    commands:
      - "eco give %player% 500"
    broadcast:
      - "&f%player% &7just won &a$500"      
  4:
    percent: 30
    needToBeOnline: true # Player must be online to receive the reward
    commands:
      - "cr give %player% diamand"
    broadcast:
      - "&7&m----------"
      - "&f%player% &7just won &ax1 diamand"
      - "&7&m----------"      
      
party:
  # The amount of votes needed
  votes_needed: 50
  
  # The command that will be executed when the number of votes is reached for each online players
  global_commands:
    - "eco give %player% 100"
    
  commands:
    - "eco give * 0.0000000009"  
    
  # Rewards that players can earn  
  rewards:
    1:
      percent: 50
      commands:
        - "give %player% minecraft:diamond 1"
    2:
      percent: 50
      commands:
        - "cr give %player% test"  
        
#Database informations
sql:
  user: "homestead"
  password: "secret"
  port: 3306
  host: "192.168.10.10"
  database: "zvoteparty"         