name: zVoteParty
author: Maxlego08
main: fr.maxlego08.zvoteparty.ZVotePartyPlugin
softdepend: [PlaceholderAPI, Votifier]
version: ${version}
website: https://groupez.dev/resources/zvoteparty.124
api-version: 1.13
commands: